### ISSUE TITLE
[compatibility] Crashes when the latest build of create is installed alongside it. Oddly it doesn't happen with the last build on the Charm (not Charm Reforged) page.

### ISSUE THREAD

**Issue by Corvus20** [svenhjol/CharmForge#22]
Title says it all, Create crashes the game during loading if Charm Reforged is used. If I use the last released forge build on the original charm page, prior to the fork/split, it works just fine. this could be an issue on Create's end, and I have submitted an issue on their page too, just wanted to cover all my bases.

Here's the message I got from the crash, more info can be provided if needed:

Thread: Render thread
Stacktrace:
at net.minecraftforge.eventbus.ListenerList.unregister(ListenerList.java:132) ~[eventbus-3.0.5-service.jar:?] {}
-- MOD create --
Details:
Mod File: create-mc1.16.3_v0.3c.jar
Failure message: Create (create) encountered an error during the sided_setup event phase
java.lang.ArrayIndexOutOfBoundsException: 192
Mod Version: mc1.16.3_v0.3c
Mod Issue URL: NOT PROVIDED
Exception message: java.lang.ArrayIndexOutOfBoundsException: 192
Stacktrace:
at net.minecraftforge.eventbus.ListenerList.unregister(ListenerList.java:132) ~[eventbus-3.0.5-service.jar:?] {}
at net.minecraftforge.eventbus.ListenerList.unregisterAll(ListenerList.java:139) ~[eventbus-3.0.5-service.jar:?] {}
at net.minecraftforge.eventbus.EventBus.unregister(EventBus.java:277) ~[eventbus-3.0.5-service.jar:?] {}
at com.simibubi.create.repack.registrate.util.OneTimeEventReceiver.unregister(OneTimeEventReceiver.java:73) ~[?:mc1.16.3_v0.3c] {re:classloading}
at com.simibubi.create.repack.registrate.util.OneTimeEventReceiver.accept(OneTimeEventReceiver.java:69) ~[?:mc1.16.3_v0.3c] {re:classloading}
at com.simibubi.create.repack.registrate.util.OneTimeEventReceiver.accept(OneTimeEventReceiver.java:22) ~[?:mc1.16.3_v0.3c] {re:classloading}
at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?] {}
at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?] {}
at net.minecraftforge.eventbus.EventBus$$Lambda$2425/541220779.invoke(Unknown Source) ~[?:?] {}
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:35.1] {re:classloading}
at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
at net.minecraftforge.fml.ModContainer$$Lambda$3004/391731193.run(Unknown Source) ~[?:?] {}
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

**Comment by F43nd1r** [comment]
The stacktrace indicates a create issue, have you reported this on their side as well?

**Comment by Corvus20** [comment]
> The stacktrace indicates a create issue, have you reported this on their side as well?

Yes, I have. I am keeping an eye out for their response.

**Comment by F43nd1r** [comment]
Linked issue https://github.com/Creators-of-Create/Create/issues/662

**Comment by F43nd1r** [comment]
Fixed in create.
