### ISSUE TITLE
Wandering Trader Config not working

### ISSUE THREAD

**Issue by Therandus93** [svenhjol/CharmForge#38]
Versions
* Charm version - 2.2.2 (Forge)
* Minecraft version - 1.16.4

Description
I have the enhanced wandering trader option enabled, so they spawn near the signal fire (yet to experience this). However the wandering trader came as normal, every 10 days to my house. I also had both the map options disabled, as they were causing lag when generating them when right clicking the trader. However they were still being present on the traders. It causes a crash sometimes when loading the maps, i think due to my world gen mods, hence why i disabled it.  But i am running optifine, so im not bothered about that. But this is more about the config not applying properly.

Optional: Steps To Reproduce
"WanderingTraderImprovements enabled" = true
	"Frequent spawning" = false
	"Trade biome maps" = false
	"Trade structure maps" = false

Ill post the crash i got, purely so you can see the list of mods i am using, in case there are any conflicts.

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 1/14/21 12:26 PM
Description: Unexpected error

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_51] {}
	at svenhjol.charm.module.WanderingTraderImprovements$StructureMapForEmeraldsTrade.func_221182_a(WanderingTraderImprovements.java:92) ~[?:2.2.2] {re:classloading}
	at net.minecraft.entity.merchant.villager.WanderingTraderEntity.func_213712_ef(SourceFile:133) ~[?:?] {re:classloading}
	at net.minecraft.entity.merchant.villager.AbstractVillagerEntity.func_213706_dY(AbstractVillagerEntity.java:99) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.merchant.villager.WanderingTraderEntity.func_230254_b_(SourceFile:105) ~[?:?] {re:classloading}
	at net.minecraft.entity.MobEntity.func_184230_a(MobEntity.java:1520) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:charm.mixins.json:MobEntityMixin,pl:mixin:APP:charm.mixins.json:accessor.MobEntityAccessor,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_190775_a(PlayerEntity.java:940) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:accessor.PlayerEntityAccessor,pl:mixin:APP:dungeons_gear.mixins.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.client.multiplayer.PlayerController.func_187097_a(PlayerController.java:364) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.optifine.override.PlayerControllerOF.func_187097_a(PlayerControllerOF.java:112) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1351) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1645) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1460) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.32.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$475/1002406942.call(Unknown Source) [forge-1.16.4-35.1.32.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_51] {}
	at svenhjol.charm.module.WanderingTraderImprovements$StructureMapForEmeraldsTrade.func_221182_a(WanderingTraderImprovements.java:92) ~[?:2.2.2] {re:classloading}
	at net.minecraft.entity.merchant.villager.WanderingTraderEntity.func_213712_ef(SourceFile:133) ~[?:?] {re:classloading}
	at net.minecraft.entity.merchant.villager.AbstractVillagerEntity.func_213706_dY(AbstractVillagerEntity.java:99) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.merchant.villager.WanderingTraderEntity.func_230254_b_(SourceFile:105) ~[?:?] {re:classloading}
	at net.minecraft.entity.MobEntity.func_184230_a(MobEntity.java:1520) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:charm.mixins.json:MobEntityMixin,pl:mixin:APP:charm.mixins.json:accessor.MobEntityAccessor,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_190775_a(PlayerEntity.java:940) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:accessor.PlayerEntityAccessor,pl:mixin:APP:dungeons_gear.mixins.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.client.multiplayer.PlayerController.func_187097_a(PlayerController.java:364) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.optifine.override.PlayerControllerOF.func_187097_a(PlayerControllerOF.java:112) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1351) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1645) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Therandus_KC'/13, l='ClientLevel', x=2012.90, y=67.00, z=5151.15]]
	Chunk stats: Client Chunk Cache: 625, 399
	Level dimension: minecraft:overworld
	Level spawn location: World: (3302,115,7871), Chunk: (at 6,7,15 in 206,491; contains blocks 3296,0,7856 to 3311,255,7871), Region: (6,15; contains chunks 192,480 to 223,511, blocks 3072,0,7680 to 3583,255,8191)
	Level time: 1721195 game time, 2980844 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2024) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.32.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$475/1002406942.call(Unknown Source) [forge-1.16.4-35.1.32.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 971883216 bytes (926 MB) / 5546967040 bytes (5290 MB) up to 6681526272 bytes (6372 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx7168m -Xms256m -XX:PermSize=256m
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.32.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.32.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.32.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.32.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.4_HD_U_G5.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.32.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.32
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		inventorysorter-1.16.1-18.1.0.jar                 |Simple Inventory Sorter       |inventorysorter               |18.1.0              |DONE      |NOSIGNATURE
		doubledoors_1.16.4-2.1.jar                        |Double Doors                  |doubledoors                   |2.1                 |DONE      |NOSIGNATURE
		UnionLib-1.16.4-3.1.5.jar                         |UnionLib                      |unionlib                      |3.1.5               |DONE      |NOSIGNATURE
		customfence-1-16-4.jar                            |Customfence                   |customfence                   |1-16-4              |DONE      |NOSIGNATURE
		areas_1.16.4-1.1.jar                              |Areas                         |areas                         |1.1                 |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.1.65.jar                           |Just Enough Items             |jei                           |7.6.1.65            |DONE      |NOSIGNATURE
		FallingTree-Forge-1.16.4-2.9.0.jar                |Falling Tree                  |falling_tree                  |2.9.0               |DONE      |NOSIGNATURE
		dungeons_mobs-1.16.4-1.0.3.jar                    |Dungeons Mobs                 |dungeons_mobs                 |1.0.3               |DONE      |NOSIGNATURE
		extraboats-1.16.4-2.0.0.jar                       |Extra Boats                   |extraboats                    |2.0.0               |DONE      |NOSIGNATURE
		create-mc1.16.3_v0.3c.jar                         |Create                        |create                        |mc1.16.3_v0.3c      |DONE      |NOSIGNATURE
		BetterCaves-1.16.3-1.0.6.jar                      |YUNG's Better Caves           |bettercaves                   |1.16.3-1.0.6        |DONE      |NOSIGNATURE
		Waystones_1.16.3-7.3.1.jar                        |Waystones                     |waystones                     |7.3.1               |DONE      |NOSIGNATURE
		ForgeEndertech-1.16.4-7.0.9.0-build.0032.jar      |Forge Endertech               |forgeendertech                |7.0.9.0             |DONE      |NOSIGNATURE
		AdFinders-1.16.4-5.0.4.0-build.0027.jar           |Advanced Finders              |adfinders                     |5.0.4.0             |DONE      |NOSIGNATURE
		villagernames_1.16.4-2.5.jar                      |Villager Names                |villagernames                 |2.5                 |DONE      |NOSIGNATURE
		TerraForged-1.16.4-0.2.0-BETA-8.jar               |TerraForged                   |terraforged                   |0.2.0-BETA-8        |DONE      |7b:73:d0:a2:c3:40:13:84:35:4f:c9:0e:2b:85:8c:08:ea:3c:3c:eb:f1:98:8b:5b:6e:ca:8a:a0:9a:cf:12:b3
		Controlling-7.0.0.11.jar                          |Controlling                   |controlling                   |7.0.0.11            |DONE      |NOSIGNATURE
		comforts-forge-1.16.4-4.0.1.0.jar                 |Comforts                      |comforts                      |1.16.4-4.0.1.0      |DONE      |NOSIGNATURE
		SereneSeasons-1.16.4-4.0.0.86-universal.jar       |Serene Seasons                |sereneseasons                 |1.16.4-4.0.0.85     |DONE      |NOSIGNATURE
		branders-wellfedmod-1.16.2-1.3.1.jar              |Well Fed Mod                  |wellfedmod                    |1.3.1               |DONE      |NOSIGNATURE
		u_team_core-1.16.4-3.1.17.191.jar                 |U Team Core                   |uteamcore                     |3.1.17.191          |DONE      |f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		mapperbase-1.16.4-2.3.0.0.jar                     |Mapper Base                   |mapperbase                    |1.16.4-2.3.0.0      |DONE      |NOSIGNATURE
		SnowRealMagic-1.16.3-2.2.2.jar                    |Snow! Real Magic!             |snowrealmagic                 |2.2.2               |DONE      |NOSIGNATURE
		Kiwi-1.16.3-3.4.1.jar                             |Kiwi                          |kiwi                          |3.4.1               |DONE      |NOSIGNATURE
		LetMeSleep-v1.3b1-1.16.4.jar                      |Let Me Sleep                  |letmesleep                    |1.3b1               |DONE      |3b:7d:be:d1:e9:dc:c0:ad:9f:f6:3d:4d:65:a8:d0:5e:da:d1:2b:b1:33:11:18:5f:0b:0d:4c:fa:9e:7c:27:41
		JEITweaker-1.16.4-1.0.1.5.jar                     |JEI Tweaker                   |jeitweaker                    |1.0.1.5             |DONE      |NOSIGNATURE
		JustEnoughResources-1.16.3-0.12.0.100.jar         |Just Enough Resources         |jeresources                   |0.12.0.100          |DONE      |NOSIGNATURE
		CraftTweaker-1.16.2-7.0.0.27.jar                  |CraftTweaker                  |crafttweaker                  |7.0.0.27            |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.32-universal.jar                |Forge                         |forge                         |35.1.32             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		absentbydesign-1.16.4-1.3.1.jar                   |Absent By Design Mod          |absentbydesign                |1.16.4-1.3.1        |DONE      |1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		scuba-gear-1.16.4-1.0.1.jar                       |Scuba Gear                    |scuba_gear                    |1.0.1               |DONE      |NOSIGNATURE
		supplementaries-0.9.19.jar                        |Supplementaries               |supplementaries               |0.9.19              |DONE      |NOSIGNATURE
		DynamicSurroundings-1.16.4-4.0.3.3.jar            |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.3.3      |DONE      |b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		forge-1.16.4-35.1.32-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		FarmersDelight-1.16.3-0.2.4b.jar                  |Farmer's Delight              |farmersdelight                |1.16.3-0.2.4b       |DONE      |NOSIGNATURE
		swingthroughgrass-1.16.4-1.5.3.jar                |SwingThroughGrass             |swingthroughgrass             |1.16.4-1.5.3        |DONE      |NOSIGNATURE
		embellishcraft-1.16.4-3.3.0.0.jar                 |EmbellishCraft                |embellishcraft                |1.16.4-3.3.0.0      |DONE      |NOSIGNATURE
		MouseTweaks-2.13-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.13                |DONE      |NOSIGNATURE
		ToolBelt-1.16.3-1.15.2.jar                        |Tool Belt                     |toolbelt                      |1.15.2              |DONE      |NOSIGNATURE
		SilentLib-1.16.3-4.9.0+63.jar                     |Silent Lib                    |silentlib                     |4.9.0+63            |DONE      |NOSIGNATURE
		AdLods-1.16.4-4.1.3.0-build.0034.jar              |Large Ore Deposits            |adlods                        |4.1.3.0             |DONE      |NOSIGNATURE
		extcaves-2.4.jar                                  |Extended Caves                |extcaves                      |2.4                 |DONE      |NOSIGNATURE
		astikorcarts-1.16.4-1.1.0.jar                     |AstikorCarts                  |astikorcarts                  |1.1.0               |DONE      |NOSIGNATURE
		jeiintegration_1.16.4-6.1.1.11.jar                |JEI Integration               |jeiintegration                |6.1.1.11            |DONE      |NOSIGNATURE
		curios-forge-1.16.4-4.0.3.3.jar                   |Curios API                    |curios                        |1.16.4-4.0.3.3      |DONE      |NOSIGNATURE
		Patchouli-1.16.4-48.jar                           |Patchouli                     |patchouli                     |1.16.4-48           |DONE      |NOSIGNATURE
		gravestone-1.16.4-1.0.8.jar                       |Gravestone Mod                |gravestone                    |1.16.4-1.0.8        |DONE      |NOSIGNATURE
		collective-1.16.4-1.53.jar                        |Collective                    |collective                    |1.53                |DONE      |NOSIGNATURE
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |DONE      |NOSIGNATURE
		Quark-r2.4-292.jar                                |Quark                         |quark                         |r2.4-292            |DONE      |NOSIGNATURE
		DoubleSlabs-1.16-3.4.10.jar                       |Double Slabs                  |doubleslabs                   |3.4.10              |DONE      |NOSIGNATURE
		HardcoreRevival_1.16.3-5.2.0.jar                  |Hardcore Revival              |hardcorerevival               |5.2.0               |DONE      |NOSIGNATURE
		Survive-1.16.4-3.0.7.jar                          |Survive                       |survive                       |1.16.4-3.0.7        |DONE      |NOSIGNATURE
		structurize-0.13.96-ALPHA-universal.jar           |Structurize                   |structurize                   |0.13.96-ALPHA       |DONE      |NOSIGNATURE
		starterkit_1.16.4-2.1.jar                         |Starter Kit                   |starterkit                    |2.1                 |DONE      |NOSIGNATURE
		minecolonies-0.13.437-RELEASE-universal.jar       |Minecolonies                  |minecolonies                  |0.13.437-RELEASE    |DONE      |NOSIGNATURE
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |DONE      |NOSIGNATURE
		solcarrot-1.16.3-1.9.8.jar                        |Spice of Life: Carrot Edition |solcarrot                     |1.16.3-1.9.8        |DONE      |NOSIGNATURE
		firstjoinmessage_1.16.4-1.0.jar                   |First Join Message            |firstjoinmessage              |1.0                 |DONE      |NOSIGNATURE
		cloth-config-forge-4.1.3.jar                      |Cloth Config v4 API           |cloth-config                  |4.1.3               |DONE      |NOSIGNATURE
		charm-forge-1.16.4-2.2.2.jar                      |Charm                         |charm                         |2.2.2               |DONE      |NOSIGNATURE
		ScalingHealth-1.16.4-4.0.2+2.jar                  |Scaling Health                |scalinghealth                 |4.0.2+2             |DONE      |NOSIGNATURE
		chiselsandbits-0.2.8-RELEASE.jar                  |Chisels & bits                |chiselsandbits                |NONE                |DONE      |NOSIGNATURE
		BetterMineshafts-Forge-1.16.3-1.1.1.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.3-1.1.1        |DONE      |NOSIGNATURE
		forge-1.16.4-geckolib-3.0.0.jar                   |GeckoLib                      |geckolib3                     |3.0.0               |DONE      |NOSIGNATURE
		ars_nouveau-1.16.4-1.10.6.jar                     |Ars Nouveau                   |ars_nouveau                   |1.10.6              |DONE      |NOSIGNATURE
		dungeons_gear-1.16.4-3.0.6.jar                    |Dungeons Gear                 |dungeons_gear                 |3.0.6               |DONE      |NOSIGNATURE
	Crash Report UUID: 0222b3d4-37a2-4d39-918f-2da68486f1a2
	Kiwi Modules: 
		kiwi:contributors
		kiwi:data
		snowrealmagic:core
		snowrealmagic:world
	Patchouli open book context: n/a
	Launched Version: forge-35.1.32
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 460.79, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, mod_resources, quark:emote_resources (incompatible)
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
	OptiFine Version: OptiFine_1.16.4_HD_U_G5
	OptiFine Build: 20201106-171901
	Render Distance Chunks: 10
	Mipmaps: 1
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL_v7.2.01pre2.zip
	OpenGlVersion: 4.6.0 NVIDIA 460.79
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by F43nd1r** [comment]
> I have the enhanced wandering trader option enabled, so they spawn near the signal fire (yet to experience this).

Signal fire spawning was removed.

Crash will be fixed in the next release.
