### ISSUE TITLE
Having Totem of undying in the equipment crashes the game, and player having it, loose it.

### ISSUE THREAD

**Issue by JurnyJudasz** [svenhjol/CharmForge#45]
[20:39:51] [Server thread/ERROR] inecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.NoSuchMethodError: net.minecraft.entity.player.PlayerInventory.func_184429_b(Lnet/minecraft/item/ItemStack;)I
	at svenhjol.charm.module.UseTotemFromInventory.tryFromInventory(UseTotemFromInventory.java:25) ~[charm:2.2.2] {re:mixin,re:classloading}
	at net.minecraft.entity.LivingEntity.redirect$zbo000$hookTryUseTotem(LivingEntity.java:3288) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_190628_d(LivingEntity.java:1101) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:1053) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.player.PlayerEntity.func_70097_a(PlayerEntity.java:814) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:accessor.PlayerEntityAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_70097_a(ServerPlayerEntity.java:597) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.player.PlayerEntity.func_71059_n(PlayerEntity.java:1100) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:accessor.PlayerEntityAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71059_n(ServerPlayerEntity.java:1291) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147340_a(ServerPlayNetHandler.java:1205) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:74) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:13) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:733) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:716) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:710) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:695) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:645) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201] {}
[20:39:51] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 159c2e64-78a6-486d-a7c1-dfc312351af4
[crash-2021-01-17_20.39.51-server.txt](https://github.com/svenhjol/CharmForge/files/5826680/crash-2021-01-17_20.39.51-server.txt)
[crash-2021-01-17_14.17.27-server.txt](https://github.com/svenhjol/CharmForge/files/5826681/crash-2021-01-17_14.17.27-server.txt)
[crash-2021-01-17_14.24.42-server.txt](https://github.com/svenhjol/CharmForge/files/5826682/crash-2021-01-17_14.24.42-server.txt)

Versions
* Charm version - 2.2.2
* Minecraft version - 1.6.4

Description
While you have totem of undying in eq got it from raid. Other player or hostile mobs attack you. Will make a crash. And loose of equipment.

Optional: Steps To Reproduce
Have totem of undying in eq, have both hands with some other equipment. Game and server crashes, you loose items.

**Comment by JurnyJudasz** [comment]
Also this warn in console.
[20:50:54] [Server thread/WARN] ixin/]: @Final field field_242962_a:Lnet/minecraft/block/AbstractBlock$IPositionPredicate; in charm.mixins.json:PortalSizeMixin should be final

**Comment by JurnyJudasz** [comment]
Why this was closed?

**Comment by F43nd1r** [comment]
It was fixed. Will be in the next release. You can watch this repository to be notified when it releases.

**Comment by JurnyJudasz** [comment]
is there a way to temporary fix it?

**Comment by F43nd1r** [comment]
You can use this intermediary build if you don't want to wait for stable release. Usual disclaimer: This build was not tested and may destroy your world, kill your cat or burn your house down. [charm.zip](https://github.com/svenhjol/CharmForge/files/5826787/charm.zip)
